---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-site
spec:
  replicas: 1
template:
    metadata:
      labels:
        app: sample-web
    spec:
      containers:
        - name: sample-web
          image: sample-web
          ports:
            - containerPort: 8080