---
apiVersion: v1
kind: Service
metadata:
  name: sample-web-service
  labels:
    app: sample-web-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    app: sample-web